server:
  port: 8080

database:
  configuration:
    url: jdbc:postgresql://localhost:5432/microsservico_email?createDatabaseIfNotExist=true
    username: postgres
    password: root

spring:
  main:
    allow-bean-definition-overriding: true

  config:
    import: file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    uri: ${RABBITMQ_URI}
    queue: ${RABBITMQ_QUEUE}
